/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

  static void main() {
    var day = new Day05(true);
    day.part1();
    day.part2();
  }
}
