/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

  static void main() {
    var day1 = new Day01(true);
    day1.part1();
    day1.part2();
  }
}
