/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

  static void main() {
    //    var day1 = new Day01(true);
    //    day1.part1();
    //    day1.part2();
    //    var day2 = new Day02(true);
    //    day2.part1();
    //    day2.part2();
    var day3 = new Day03(true);
    day3.part1();
    day3.part2();
  }
}
